### ISSUE TITLE
Crashes if range spans 0 elements

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/dataview#13]
DataView crashes if one of the input ranges spans 0 elements.  While generally not intended, this can happen if changing the range to something new where the old endpoint becomes the new start point.  Error log below.

Traceback (most recent call last):
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 521, in updateAxesFieldsAction
    self.makePlot()
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 657, in makePlot
    self.plot1D()
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 750, in plot1D
    datamax = np.max(data)
  File "/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2334, in amax
    initial=initial)
  File "/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 83, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
Abort trap: 6

**Comment by pheuer** [comment]
This should be resolved now
