### ISSUE TITLE
Crash related to data range for plot

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/dataview#15]
DataView crashes for some reason when changing the Data Range for the plot.  Error log below:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 149, in draw_path
    self._renderer.draw_path(gc, path, transform, rgbFace)
OverflowError: In draw_path: Exceeded cell block limit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 550, in updateDataUnits
    self.makePlot()
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 657, in makePlot
    self.plot1D()
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 759, in plot1D
    self.canvas.draw()
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2628, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/lines.py", line 771, in draw
    renderer.draw_path(gc, tpath, affine.frozen())
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 151, in draw_path
    raise OverflowError("Exceeded cell block limit (set "
OverflowError: Exceeded cell block limit (set 'agg.path.chunksize' rcparam)
Abort trap: 6

**Comment by pheuer** [comment]
What kind of dataset were you trying to plot (bdot data? how many axes?) and what kind of bounds were you trying to set? Was this still in the default units?
