### ISSUE TITLE
DataView crashes if one of the displayed axes is not an array

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/dataview#2]
If you select an axis that is not an array (i.e. only one element, perhaps from averaging), DataView crashes. See error log below:

Traceback (most recent call last):
File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 434, in updateAxesFieldsAction
self.makePlot()
File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 516, in makePlot
self.plot2D()
File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 682, in plot2D
cs = self.canvas_ax.contourf(hax, vax, data, levels, cmap=colormap)
File "/anaconda3/lib/python3.7/site-packages/matplotlib/init.py", line 1810, in inner
return func(ax, *args, **kwargs)
File "/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 6239, in contourf
contours = mcontour.QuadContourSet(self, *args, **kwargs)
File "/anaconda3/lib/python3.7/site-packages/matplotlib/contour.py", line 887, in init
kwargs = self._process_args(*args, **kwargs)
File "/anaconda3/lib/python3.7/site-packages/matplotlib/contour.py", line 1493, in _process_args
x, y, z = self._contour_args(args, kwargs)
File "/anaconda3/lib/python3.7/site-packages/matplotlib/contour.py", line 1551, in _contour_args
x, y, z = self._check_xyz(args[:3], kwargs)
File "/anaconda3/lib/python3.7/site-packages/matplotlib/contour.py", line 1585, in _check_xyz
raise TypeError("Input z must be a 2D array.")
TypeError: Input z must be a 2D array.
Abort trap: 6

**Comment by pheuer** [comment]
Interesting: I'm having trouble reproducing this with the example_data.hdf5 file now included in the repo. If I set "chan" (which only has one element) as the axis, I get an error in the program and no plot is made, but it doesn't crash out. I'll keep looking into it: let me know if you observe any other related behavior.

**Comment by pheuer** [comment]
It appears this error (and others) crash the program when run in terminal, but are non-fatal when running in Spyder. I'll work on patching them.

**Comment by pheuer** [comment]
This error should be resolved in the latest update
