### ISSUE TITLE
Bug handling directory names

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/dataview#20]
For some reason, DataView crashes when trying to save images to a directory named something like "run34.01"

`Traceback (most recent call last):
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 1328, in runMovie
    self.saveMovieFrame(ax_name, i)
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 1292, in saveMovieFrame
    self.figure.savefig(saveframe)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 2094, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 88, in print_figure
    super().print_figure(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2075, in print_figure
    **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 521, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 407, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 392, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dereks/Desktop/Research/Experiments/2019/LAPD 09-19/Analysis/Movies/run34/time_0.00.png'`

**Comment by pheuer** [comment]
I've had issues with filenames with periods in them in general: using "run34_01" or something similar should resolve the issue temporarily until we figure out where it causes a problem.
