### ISSUE TITLE
DataView crashes if cancel loading an H5 file

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/dataview#4]
DataView crashes if you cancel the load H5 dialog.  Error log below:

Traceback (most recent call last):
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 247, in fileDialog
    with h5py.File(self.filepath, 'r') as f:
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
ValueError: Invalid file name (invalid file name)
Abort trap: 6

**Comment by pheuer** [comment]
This issue is resolved in the latest update by better file handling.
