### ISSUE TITLE
DataView crashes when switching H5 files

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/dataview#5]
After loading one H5 file, when loading a new H5 file DataView crashes.  Error log below:

load
/Volumes/Antares/Research/Experiments/2019/LAPD_Jan2019/BDOT/run31_LAPD_C6_full.hdf5
[]
Traceback (most recent call last):
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 434, in updateAxesFieldsAction
    self.makePlot()
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 514, in makePlot
    self.plot1D()
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 561, in plot1D
    a = int(d['field1'].text())
KeyError: 'field1'
Abort trap: 6

**Comment by pheuer** [comment]
This issue is resolved in the latest update by better file handling.
